### ISSUE TITLE
Matching Score

### ISSUE THREAD

**Issue by Naysanado** [ufukefe/DFM#6]
Hello, how can I get the confidence of matching point pairs? For example, among the 1000 matching point pairs generated, which have high matching accuracy and which have low matching accuracy

**Comment by ufukefe** [comment]
Hi, sorry for late reply. 

Unfortunately, there is not exist a specific confidence for each match, but you can use _score_A2B_  for that purpose. 

In fact, the confidence of any match will be related to the its own score and its parent matches (scores of the matches on the previous layers)
